name: Flawfinder Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flawfinder-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Flawfinder
      run: pip install flawfinder
    - name: Run Flawfinder
      run: flawfinder ./ --context
